from typing import TypedDict, List, Dict, Any

class RagAgentState(TypedDict):
    original_query: str          # The initial user prompt
    current_search_query: str    # The optimized query (rewritten if healing occurs)
    retrieved_chunks: List[Dict[str, Any]] # Combined chunks from all 3 engines
    draft_answer: str            # Current response generated by Groq
    critique_score: float        # Groundedness evaluation score from Gemini
    critique_feedback: str       # Reason for failure if model hallucinated
    loop_count: int              # Counter to break the loop at Max 3 retries
